### ISSUE TITLE
Not able to build the windows app with the plugin installed.

### ISSUE THREAD

**Issue by crossdsection** [litehelpers/cordova-sqlite-evplus-ext-legacy-build-free#10]
I was able to build the app without the plugin,

But if I try installing the plugin and then building it causes the following error.

`C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppCommon.targets(242,5): error MSB6006: "CL.exe" exited with code -1073741515. [C:\Project\Bizom\plugins\cordova-sqlite-evfree\src\windows\SQLite3-WinRT\SQLite3\SQLite3.WindowsPhone\SQLite3.WindowsPhone.vcxproj]`

This[1073741515] error code refers to missing dll, I reinstalled MSBuildTools. But still got similar error.  

This started happening after I updated Cordova.

**Comment by brody2consult** [comment]
Did you specify the CPU architecture for the build?

**Comment by crossdsection** [comment]
No I didn't.

**Comment by crossdsection** [comment]
Can I get some help in adding the CPU architecture? I tried things, but probably in the wrong way.

`cordova build windows -archs="x86 arm"`

This also returned the same error.

**Comment by brody2consult** [comment]
I think you should only use one CPU architecture in the build flags. I generally test the Windows version by building it in the Visual Studio GUI.

**Comment by crossdsection** [comment]
Ok, I will try that. Will the plugin works with AnyCpu architecture?

**Comment by brody2consult** [comment]
No. While most of the Cordova plugins just use JavaScript for Windows this plugin has a C/C++ component.

**Comment by crossdsection** [comment]
After trying with all possible architecture versions for windows[ the app builds for android ], the error is same. Using GUI as well as CLI.

**Comment by brody2consult** [comment]
Please try again with a fresh, clean project. I think there is something wrong with the installation in your project.

The build should explain **why** it cannot build. In case of a missing SQLite or SQLite3 library or winmd file, there should be a message **why** it could not build the library or winmd.

**Comment by crossdsection** [comment]
I fixed it.. by removing and adding platform... issue can be closed now.. thanks for help...
