### ISSUE TITLE
FireOS support

### ISSUE THREAD

**Issue by scottjpearson** [litehelpers/cordova-sqlite-evplus-ext-legacy-build-free#2]
Any reason FireOS support has been left off? My understanding is that its orientation is somewhat similar to Android. Could this be something I adapt on my own?

**Comment by brody2consult** [comment]
> Any reason FireOS support has been left off? My understanding is that its
> orientation is somewhat similar to Android. Could this be something I adapt
> on my own?

It should be no problem to build it for Amazon FireOS as well but then you
would have to test it as well.

One thing is that I am not 100% sure that the native libraries would work
the same way. You may have to unpack them like I did for the main project.

If someone can run the test suite in spec/www and issue a pull request if
it works, it may help some others.

Also for the main project, I would be curious if the native libraries would
work the same way on FireOS.

**Comment by scottjpearson** [comment]
Cool. So basically, I’m just going to point the java files to amazon-fireos in the plugin.xml and see what happens. I’ll report back.

Scott J. Pearson
REDCap Core Programmer, Project REDCap
REDCap Mobile App
http://projectredcap.orghttp://projectredcap.org/
Vanderbilt Institute for Clinical and Translational Research (VICTR)
615-322-6039 (o)

**Comment by scottjpearson** [comment]
So I’m getting the same old response. :-(

D/CordovaLog(27245): file:///android_asset/www/plugins/cordova-sqlite-evfree/www/SQLitePlugin.js: Line 231 : OPEN database: xxxxxx failed, aborting any pending transactions

I/chromium(27245): [INFO:CONSOLE(231)] "OPEN database: xxxxxx failed, aborting any pending transactions"

D/CordovaLog(27245): file:///android_asset/www/plugins/cordova-sqlite-evfree/www/SQLitePlugin.js: Line 97 : Could not open database

I/chromium(27245): [INFO:CONSOLE(97)] "Could not open database"

Scott J. Pearson
REDCap Core Programmer, Project REDCap
REDCap Mobile App
http://projectredcap.orghttp://projectredcap.org/
Vanderbilt Institute for Clinical and Translational Research (VICTR)
615-322-6039 (o)

**Comment by brody2consult** [comment]
> So I’m getting the same old response. :-(

Can you try the main Cordova-sqlite-storage version on Fire OS and see if
you can open a database with that version?

If so, then I think we can conclude the native libraries are not working
with FireOS for some reason. It may be due to packaging them in the jar or
perhaps something else. I can unjar the native libraries later today or
tonight.

**Comment by scottjpearson** [comment]
No, they both fail.

Scott J. Pearson
REDCap Core Programmer, Project REDCap
REDCap Mobile App
http://projectredcap.orghttp://projectredcap.org/
Vanderbilt Institute for Clinical and Translational Research (VICTR)
615-322-6039 (o)

**Comment by brody2consult** [comment]
Just raised cordova/cordova-discuss#32

**Comment by brody2consult** [comment]
Answer by @stevengill in https://github.com/cordova/cordova-discuss/issues/32#issuecomment-167021676:

> Amazon committers have been gone from the project for a while. Last we heard they said to target android to deploy to fireos 5.0+ devices. We are in the process of removing support of fireos from cordova [1].
> 
> [1] https://issues.apache.org/jira/browse/CB-10121
> 
> LMK if you have more questions!
